places_to_vist_US = ["New York City", "Seattle", "Chicago", "Miami"]
places_to_vist_SE_Asia = ["Saigon", "Singapore", "Bali", "Hanoi"]
things_to_do_US = ["City tour", "Trying out expensive resturuants", "Go to the casino", "Go to a concert"]
things_to_do_SE_Asia = ["Go on a boat tour", "Go hiking", "Street food tour", "Visit a religious temple"]
transportation_US = ["Car", "Train", "Plane"]
transportation_SE_Asia = ["Boat", "Plane"]
places_to_stay_US = ["AirBnB", "Hotel", "Motel"]
places_to_stay_SE_Asia = ["Hotel", "Hostel", "AirBnB"]